export const attendedSessionsStyles = {
  scrollView: {
    flex: 1,
    width: '$full',
  },
  container: {
    flex: 1,
    bg: '$white',
    borderWidth: 1,
    borderColor: '$borderLight300',
    borderRadius: '$lg',
    m: '$4',
    p: '$6',
  },
  content: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  emptyTitle: {
    fontSize: '$xl',
    fontWeight: '$bold',
    color: '$textForeground',
    textAlign: 'center' as const,
  },
  emptyDescription: {
    fontSize: '$md',
    color: '$textMutedForeground',
    textAlign: 'center' as const,
  },
  loadingContainer: {
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    py: '$10' as const,
    width: '100%' as const,
  },
  headerHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    width: '100%' as const,
    mb: '$4' as const,
  },
  headerTitleText: {
    fontSize: '$md' as const,
    fontWeight: '$bold' as const,
    color: '$textPrimary' as const,
  },
  filterSelectBox: {
    width: 140 as const,
  },
  listVStack: {
    space: 'md' as const,
    width: '100%' as const,
  },
  card: (isAttended: boolean) => ({
    bg: isAttended ? '$success50' : '$white',
    borderWidth: 1,
    borderColor: isAttended ? '#a7f3d0' : '$borderLight200',
    borderRadius: 16,
    p: '$4' as const,
    width: '100%' as const,
  }),
  cardHeaderHStack: {
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    width: '100%' as const,
    space: 'sm' as const,
  },
  cardTitleHStack: {
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    space: 'sm' as const,
    flex: 1,
  },
  cardTitleText: {
    fontSize: '$sm' as const,
    fontWeight: '$bold' as const,
    color: '$textPrimary' as const,
  },
  statusBadge: (isAttended: boolean) => ({
    bg: isAttended ? '$success50' : '$backgroundLight100',
    borderWidth: 1,
    borderColor: isAttended ? '#a7f3d0' : '$borderColor',
    borderRadius: '$full' as const,
    paddingLeft: 8 as const,
    paddingRight: 8 as const,
    paddingTop: 2 as const,
    paddingBottom: 2 as const,
  }),
  statusBadgeText: (isAttended: boolean) => ({
    fontSize: 12 as const,
    color: isAttended ? '$success600' : '$textMuted',
    fontWeight: '$medium' as const,
  }),
  chevronIconProps: {
    size: 18,
    color: '$textMuted',
  },
  subtitleText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
    mt: '$0.5' as const,
  },
  metaRowHStack: {
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    columnGap: 32 as const,
    rowGap: 8 as const,
    mt: '$3' as const,
  },
  metaItemHStack: {
    alignItems: 'center' as const,
    space: 'xs' as const,
  },
  metaText: {
    fontSize: '$xs' as const,
    color: '$textSecondary' as const,
  },
  deliveryText: {
    fontSize: '$xs' as const,
    color: '$success600' as const,
    fontWeight: '$medium' as const,
    textTransform: 'capitalize' as const,
  },
  tagsRowHStack: {
    flexWrap: 'wrap' as const,
    columnGap: 8 as const,
    rowGap: 8 as const,
    mt: '$3' as const,
  },
  tagBadge: (isPrimary: boolean) => ({
    bg: isPrimary ? '#FFEDD5' : '$backgroundLight100',
    borderRadius: '$full' as const,
    paddingLeft: 10 as const,
    paddingRight: 10 as const,
    paddingTop: 2 as const,
    paddingBottom: 2 as const,
  }),
  tagBadgeText: (isPrimary: boolean) => ({
    fontSize: 11 as const,
    color: isPrimary ? '#C2410C' : '$textSecondary',
    fontWeight: '$medium' as const,
  }),
} as const;
